name: Test

on:
  pull_request:
    branches: ["master"]
    paths-ignore:
    - 'README.md'
    - 'benchmark/**'
    - '.github/workflows/release.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: true
      matrix:
        include:
        - elixir: 1.12.x
          otp: 23
          os: ubuntu-20.04
        - elixir: 1.13.x
          otp: 24
          os: ubuntu-20.04
        - elixir: 1.14.x
          otp: 25
          os: ubuntu-latest
        - elixir: 1.17.x
          otp: 26
          os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup erlang/elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Restore dependencies cache
      id: deps
      uses: actions/cache@v3
      with:
        path: deps
        key: deps-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}
          deps-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

    - name: Install dependencies
      if: steps.deps.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Restore compile cache
      id: compile
      uses: actions/cache@v3
      with:
        path: _build
        key: compile-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}-${{ hashFiles('**/mix.lock')
          }}
        restore-keys: |
          compile-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}
          compile-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

    - name: Compile dependencies
      if: steps.compile.outputs.cache-hit != 'true'
      run: mix deps.compile

    - name: Compile code
      run: mix compile --warnings-as-errors

    - name: Run mix format
      run: mix format --check-formatted --dry-run

    - name: Run mix credo
      run: mix credo

    - name: Run tests
      run: mix test

    - name: Restore PLT cache
      id: plt
      uses: actions/cache/restore@v3
      with:
        path: priv/plts
        key: plt-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          plt-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}
          plt-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

    - name: Create PLTs
      if: steps.plt.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mkdir -p priv/plts/core.plt
        mkdir -p priv/plts/local.plt
        mix dialyzer --plt

    - name: Save PLT cache
      uses: actions/cache/save@v3
      if: steps.plt.outputs.cache-hit != 'true'
      with:
        path: priv/plts
        key: plt-${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.ref }}-${{ hashFiles('**/mix.lock') }}

    - name: Run dialyzer
      run: mix dialyzer --format github
